name: nuxtjs-demo 
displayName: Nuxt.js 项目模版
author: Tencent Cloud, Inc.
org: Tencent Cloud, Inc.
description:  Deploy an Nuxt.js app via SCF and Apigateway
description-i18n:
  zh-cn: 快速部署一个 Nuxt.js 基础应用
type: template 
keywords: tencent, Nuxtjs, nodejs, SCF, APIGateway
repo: https://github.com/serverless-components/tencent-examples/tree/master/nuxt-demo
readme:  https://github.com/serverless-components/tencent-examples/blob/master/nuxt-demo/README.md
license: MIT 
src: 
  src: ../../nuxtjs-demo
  exclude: 
     - '**/node_modules'

