component: express # (required) name of the component. In that case, it's express.
name: expressDemo # (required) name of your express component instance.
app: appDemo # (optional) serverless dashboard app. default is the same as the name property.

inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
